### ISSUE TITLE
can't find models

### ISSUE THREAD

**Issue by Sparkxxx** [BMW-InnovationLab/BMW-TensorFlow-Inference-API-CPU#9]
Hello there, 

I'm getting started with ai and cv and I am trying to test the app but I have a hard time finding suitable models or configuring the application, both tensorflow and yolo.

What I've done so far beside building and running the container:
1. Downloaded https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API models and pbtxt files, namely Inception-SSD v2 and MobileNet-SSD v3.
2. Removed all other files from archive and changed names to frozen_inference_graph.pb, object-detection.pbtxt
3. created config.json (not Config.json as stated in docs) with the following content:
`
{
      "inference_engine_name": "tensorflow_detection",
      "confidence": 60,
      "predictions": 15,
      "number_of_classes": 2,
      "framework": "tensorflow",
      "type": "detection",
      "network": "mobilenet"
  }
`
4. Ran the container and when trying to load models I get this error 
`
lab_tensorflow | a bytes-like object is required, not 'str'
lab_tensorflow | Error loading model
lab_tensorflow | INFO:     10.xx.0.xx:63174 - "GET /load HTTP/1.1" 200 OK
`
Questions:
1. What pretrained models are suitable and where to find them?
2. What is the purpose of models_hash?
3. What is / where to find the right config.json "network" value, is mine correct?

Thank you.

**Comment by hadikoub** [comment]
What pretrained models are suitable and where to find them?
This application is targeted to be used for the trained model from our training tool [Link](https://github.com/BMW-InnovationLab/BMW-TensorFlow-Training-GUI)

What is the purpose of models_hash?
models_hash is used internally to assign a unique ID to each model so that you don't need to reference a model by its name but rather by its ID. This id doesn't change for the model on multiple loads and run. 

What is / where to find the right config.json "network" value, is mine correct?
if you're meaning `/` in the error this is the API endpoint path. 
the network you are using `mobilenet` is not supported by our training API you can check the supported training models from [Link](https://github.com/BMW-InnovationLab/BMW-TensorFlow-Training-GUI/blob/master/training_api/assets/networks.json)
